# Generated by Django 5.1 on 2024-08-21 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_curso_deleted_at_curso_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='estudante',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='estudante',
            name='is_deleted',
        ),
    ]
